services:
  prodflow_db:
    container_name: 'prodflow_db'
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prodflow
    ports:
      - "5435:5432"
  prodflow_db_test:
    container_name: 'prodflow_db_test'
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5436:5432"


